#!/bin/bash
#not used in the sysvinit version for while or maybe never. 

doit(){ 
export hostname="$(</etc/hostname)" 
while : ; do 
getty 9600 $1 
done 
}

case "$1" in tty*) 
doit $1&

;;
*) echo "Usage texasflood-tty tty_number, example: texasflood-tty tty3" 
;; 
esac
 
