#!/bin/bash
#KDE speed helper

#If you are using KDE or a slow environment, this can improve the speed a few seconds... 
#vmtouch must be installed in your system to get this working. 
source /etc/texasflood.conf



f_vmtouch(){
      /usr/local/bin/vmtouch -t $1 &>/dev/null
}

cat /etc/texasflood.nightmare | grep -v "#" | while read library; do 
     f_vmtouch "$library" & 
done

exit 0

